/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32F1X)
#include <stm32f1xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32F2X)
#include <stm32f2xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32F4X)
#include <stm32f4xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32F7X)
#include <stm32f7xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32H5X)
#include <stm32h5xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7RSX)
#include <stm32h7rsxx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7X)
#include <stm32h7xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32L1X)
#include <stm32l1xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32L4X)
#include <stm32l4xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32L5X)
#include <stm32l5xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32MP1X)
#include <stm32mp1xx_ll_sdmmc.h>
#elif defined(CONFIG_SOC_SERIES_PY32U5X)
#include <stm32u5xx_ll_sdmmc.h>
#endif
