/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32MP1X)
#include <stm32mp1xx_ll_ipcc.h>
#elif defined(CONFIG_SOC_SERIES_PY32WBX)
#include <stm32wbxx_ll_ipcc.h>
#elif defined(CONFIG_SOC_SERIES_PY32WLX)
#include <stm32wlxx_ll_ipcc.h>
#endif
