/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32G4X)
#include <stm32g4xx_ll_cordic.h>
#elif defined(CONFIG_SOC_SERIES_PY32H5X)
#include <stm32h5xx_ll_cordic.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7RSX)
#include <stm32h7rsxx_ll_cordic.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7X)
#include <stm32h7xx_ll_cordic.h>
#elif defined(CONFIG_SOC_SERIES_PY32U5X)
#include <stm32u5xx_ll_cordic.h>
#endif
