/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32H5X)
#include <stm32h5xx_ll_icache.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7RSX)
#include <stm32h7rsxx_ll_icache.h>
#elif defined(CONFIG_SOC_SERIES_PY32L5X)
#include <stm32l5xx_ll_icache.h>
#elif defined(CONFIG_SOC_SERIES_PY32U5X)
#include <stm32u5xx_ll_icache.h>
#elif defined(CONFIG_SOC_SERIES_PY32WBAX)
#include <stm32wbaxx_ll_icache.h>
#endif
