/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32C0X)
#include <stm32c0xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F0X)
#include <stm32f0xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F1X)
#include <stm32f1xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F2X)
#include <stm32f2xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F3X)
#include <stm32f3xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F4X)
#include <stm32f4xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32F7X)
#include <stm32f7xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32G0X)
#include <stm32g0xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32G4X)
#include <stm32g4xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32H5X)
#include <stm32h5xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7RSX)
#include <stm32h7rsxx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7X)
#include <stm32h7xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32L0X)
#include <stm32l0xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32L1X)
#include <stm32l1xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32L4X)
#include <stm32l4xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32L5X)
#include <stm32l5xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32U0X)
#include <stm32u0xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32U5X)
#include <stm32u5xx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32WB0X)
#include <stm32wb0x_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32WBAX)
#include <stm32wbaxx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32WBX)
#include <stm32wbxx_ll_iwdg.h>
#elif defined(CONFIG_SOC_SERIES_PY32WLX)
#include <stm32wlxx_ll_iwdg.h>
#endif
