/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32C0X)
#include <stm32c0xx_ll_bus.h>
#elif defined(CONFIG_SOC_SERIES_PY32F0X)
#include <stm32f0xx_ll_bus.h>
#endif
