/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_PY32G0X)
#include <stm32g0xx_ll_ucpd.h>
#elif defined(CONFIG_SOC_SERIES_PY32G4X)
#include <stm32g4xx_ll_ucpd.h>
#elif defined(CONFIG_SOC_SERIES_PY32H5X)
#include <stm32h5xx_ll_ucpd.h>
#elif defined(CONFIG_SOC_SERIES_PY32H7RSX)
#include <stm32h7rsxx_ll_ucpd.h>
#elif defined(CONFIG_SOC_SERIES_PY32L5X)
#include <stm32l5xx_ll_ucpd.h>
#elif defined(CONFIG_SOC_SERIES_PY32U5X)
#include <stm32u5xx_ll_ucpd.h>
#endif
